# Generated by Django 5.1.3 on 2025-03-08 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brokers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brokerId', models.SmallIntegerField(unique=True)),
                ('brokerName', models.CharField(max_length=255, unique=True)),
                ('className', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('symbol', models.CharField(max_length=40)),
                ('symbolFinvasia', models.CharField(default='', max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('expiry', models.CharField(blank=True, max_length=40, null=True)),
                ('strike', models.DecimalField(decimal_places=10, max_digits=30)),
                ('lotSize', models.IntegerField()),
                ('instrumentType', models.CharField(max_length=24)),
                ('exchSeg', models.CharField(max_length=40)),
                ('segment', models.CharField(default='', max_length=40)),
                ('tickSize', models.DecimalField(decimal_places=10, max_digits=30)),
                ('optionType', models.CharField(default='', max_length=2)),
                ('GNGD', models.DecimalField(decimal_places=5, default=1, max_digits=12)),
                ('precision', models.IntegerField(default=2)),
                ('multiplier', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Strategis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('className', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=80)),
                ('apiKey', models.CharField(max_length=40)),
                ('clientId', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('factor2', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('factor2Secret', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('vendorCode', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('reqToken', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('feedToken', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('acccessToken', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('apiSecret', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_brokeraccs', to=settings.AUTH_USER_MODEL)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_broker', to='trading.brokers')),
            ],
        ),
        migrations.CreateModel(
            name='JobbingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('symbol', models.CharField(blank=True, max_length=40, null=True)),
                ('orderId', models.CharField(max_length=20)),
                ('tradeDate', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orderType', models.CharField(max_length=4)),
                ('intraday', models.BooleanField(default=False)),
                ('currStock', models.IntegerField()),
                ('status', models.CharField(max_length=40)),
                ('updatedOn', models.DateTimeField(blank=True, null=True)),
                ('orderCategory', models.CharField(blank=True, default='Normal', max_length=12, null=True)),
                ('exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_Jobbing_Exchange', to='trading.exchanges')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_cycleTarget', to='trading.brokeraccounts')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_cycleLog', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobbingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('stockInitial', models.IntegerField()),
                ('buyLot', models.IntegerField()),
                ('buyTick', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sellLot', models.IntegerField(default=0)),
                ('sellTick', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('priceBase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('priceCurrent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stockCurrent', models.IntegerField(default=0)),
                ('stockMax', models.IntegerField(default=0)),
                ('stockMin', models.IntegerField(default=0)),
                ('dayOrders', models.IntegerField(default=3)),
                ('isActive', models.BooleanField(default=False)),
                ('simulate', models.BooleanField(default=True)),
                ('symbol', models.CharField(blank=True, max_length=40, null=True)),
                ('orderCatagory', models.CharField(blank=True, default='Normal', max_length=12, null=True)),
                ('gttBuyBuffer', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('gttSellBuffer', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('wait', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=1)),
                ('exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_Jobbing_Exchange', to='trading.exchanges')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trading.brokeraccounts')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_cycleOrder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_MSession_Broker', to='trading.brokers')),
                ('exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_MSession_Exchange', to='trading.exchanges')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currStatus', models.CharField(max_length=10)),
                ('forceStop', models.BooleanField(default=False)),
                ('taskId', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_statusstrategy', to='trading.strategis')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_statususer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
