# Generated by Django 5.1.3 on 2026-01-18 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_remove_brokers_created_at_remove_brokers_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('symbol', models.CharField(blank=True, max_length=40, null=True)),
                ('orderId', models.CharField(max_length=20)),
                ('tradeDate', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orderType', models.CharField(max_length=4)),
                ('intraday', models.BooleanField(default=False)),
                ('currStock', models.IntegerField()),
                ('status', models.CharField(max_length=40)),
                ('updatedOn', models.DateTimeField(blank=True, null=True)),
                ('orderCategory', models.CharField(blank=True, default='Normal', max_length=12, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_Jobbing_Exchange', to='trading.exchanges')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_cycleTarget', to='trading.brokeraccounts')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_cycleLog', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SwingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=40)),
                ('stockInitial', models.IntegerField()),
                ('lot', models.IntegerField()),
                ('slLot', models.IntegerField(default=0)),
                ('stopLoss', models.DecimalField(decimal_places=2, max_digits=7)),
                ('gap', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('priceCurrent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stockCurrent', models.IntegerField(default=0)),
                ('stockMax', models.IntegerField(default=0)),
                ('stockMin', models.IntegerField(default=0)),
                ('dayOrders', models.IntegerField(default=3)),
                ('isActive', models.BooleanField(default=False)),
                ('simulate', models.BooleanField(default=True)),
                ('symbol', models.CharField(blank=True, max_length=40, null=True)),
                ('orderCatagory', models.CharField(blank=True, default='Normal', max_length=12, null=True)),
                ('wait', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=1)),
                ('useSlLot', models.BooleanField(default=False)),
                ('lastExecutedOrderType', models.CharField(blank=True, max_length=4, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_Jobbing_Exchange', to='trading.exchanges')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trading.brokeraccounts')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_cycleOrder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
