# Generated by Django 5.1.3 on 2026-02-15 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_swinglog_swingsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scripts',
            name='expiryDate',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='jobbinglog',
            index=models.Index(fields=['user_id', 'tradeDate'], name='trading_job_user_id_7bad2c_idx'),
        ),
        migrations.AddIndex(
            model_name='scripts',
            index=models.Index(fields=['exchSeg', 'symbol'], name='trading_scr_exchSeg_0ec3b2_idx'),
        ),
        migrations.AddIndex(
            model_name='scripts',
            index=models.Index(fields=['exchSeg', 'token'], name='trading_scr_exchSeg_d5c1eb_idx'),
        ),
        migrations.AddIndex(
            model_name='scripts',
            index=models.Index(fields=['token'], name='trading_scr_token_b11d5c_idx'),
        ),
        migrations.AddIndex(
            model_name='scripts',
            index=models.Index(fields=['symbol'], name='trading_scr_symbol_9caf80_idx'),
        ),
        migrations.AddIndex(
            model_name='scripts',
            index=models.Index(fields=['exchSeg', 'instrumentType'], name='trading_scr_exchSeg_bf4068_idx'),
        ),
        migrations.AddIndex(
            model_name='swinglog',
            index=models.Index(fields=['user_id', 'tradeDate'], name='trading_swi_user_id_ea9cfc_idx'),
        ),
    ]
