"""
Django settings for yantra project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import environ
from datetime import datetime
from datetime import timedelta
import os
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if env('DEBUG') == 1 else False

ALLOWED_HOSTS = ['127.0.0.1','localhost','103.212.121.121']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'userauth',   
    'permissions',
    'utils',
    'social',
    'mainapp',
    'trading',
    'celery',
    'django_celery_results',
    'django_celery_beat', 
    'rest_framework',
    'rest_framework.authtoken',   
    'rest_framework_simplejwt',   
    'django_filters', 
    'generic_relations',   
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'yantra.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yantra.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': env('ORM_DATABASE_DATABASE'),
#         'USER': env('ORM_DATABASE_USER'),
#         'PASSWORD': env('ORM_DATABASE_PWD'),
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

REDIS_LOCATION = f"redis://{env('REDIS_HOST')}:{env('REDIS_PORT')}"
# "redis://username:password@127.0.0.1:6379"
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_LOCATION,
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'fusioncorpmailbot@gmail.com'
EMAIL_HOST_PASSWORD = 'srageuokewwzurjf'
EMAIL_PORT = 587

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR , 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CELERY_BROKER_URL = 'redis://127.0.0.1:6379'
ACCEPT_CONTENT = ['application/json']
RESULT_SERIALIZER = 'json'
TASK_SERIALIZER = 'json'
TIMEZONE = 'UTC'

RESULT_BACKEND = 'django-db'

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (

        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']

}



REDIS_PASSWORD = env('REDIS_PWD', default=None)
REDIS_LOCATION = 'redis://127.0.0.1:6379/'
REDIS_LOCK_EXPIRY = env('REDIS_LOCK_EXPIRY', default=10)
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
ACCEPT_CONTENT = ['application/json']
RESULT_SERIALIZER = 'json'
TASK_SERIALIZER = 'json'
TIMEZONE = 'Asia/Kolkata'





# Celery Beat Setting
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": CELERY_BROKER_URL,
    }
}

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = "access-control-allow-origin"
CORS_ALLOWED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://127.0.0.1:9000',
    'https://dhananjayfinserv.com'
]

CORS_ALLOW_HEADERS = (
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
)

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=180),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (

        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']

}

# Handle Task using Celery or Thread
TRADING_HANDLE_TASKS = env('TRADING_HANDLE_TASKS',default='CELERY')
TRADING_LOG_LEVEL = env('TRADING_LOG_LEVEL', default='WARNING')

LOGGING = {
    # ... 
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            # '()': 'django.utils.log.ServerFormatter',
            'format': '[ %(asctime)s ] (%(process)d) %(lineno)d %(name)s - %(levelname)s - %(message)s', #(%(username)s)
            # 'style': '{',
        },
        
        'simple': {
            # 'format': '%(levelname)s %(message)s'
            'format':'[ %(asctime)s ] (%(process)d) %(lineno)d %(name)s - %(levelname)s - %(message)s'
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            # 'filename':f"{datetime.now().strftime('%m_%d_%Y_%H_%M_%S')}.log",
            'filename': os.path.join(BASE_DIR, f"{datetime.now().strftime('%m_%d_%Y')}.log"),
            'formatter': 'verbose',
        },
        'filedebug': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            # 'filename':f"{datetime.now().strftime('%m_%d_%Y_%H_%M_%S')}.log",
            'filename': os.path.join(BASE_DIR, f"debug_{datetime.now().strftime('%m_%d_%Y')}.log"),
            'formatter': 'verbose',
        },
        'fileinfo': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            # 'filename':f"{datetime.now().strftime('%m_%d_%Y_%H_%M_%S')}.log",
            'filename': os.path.join(BASE_DIR, f"info_{datetime.now().strftime('%m_%d_%Y')}.log"),
            'formatter': 'verbose',
        },                
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        }        
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # 'trading.views': {
        #     'handlers': ['console', 'file'],
        #     'level': 'DEBUG',
        #     'formatter': 'verbose',
        #     'propagate': False,
        #     # ...
        # },
        'social.views': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'formatter': 'verbose',
            'propagate': False,
            # ...
        },
        'trading': {
            'handlers': ['console', 'filedebug','fileinfo'],
            'level': 'DEBUG',
            'formatter': 'verbose',
            'propagate': False,
            # ...
        },                    
        # 'trading.views.jobs': {
        #     'handlers': ['console', 'file'],
        #     'level': 'DEBUG',
        #     'formatter': 'verbose',
        #     'propagate': DEBUG,
        #     # ...
        # }        
        # "my_app.views": {
        #     # ...
        # },
        # "my_app.views.private": {
        #     # ...
        #     "propagate": False,
        # },
    },
    'level': TRADING_LOG_LEVEL
}